name: Update GTFS Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  update:
    runs-on: ubuntu-latest  # Uses the latest version of Ubuntu

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3  # Updated to latest version
      with:
        fetch-depth: 0  # Ensures full history is available for git operations

    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to latest version
      with:
        python-version: '3.x'  # Specify Python version (e.g., 3.9)

    - name: Install dependencies
      run: |
        pip install requests  # Installs the required Python packages

    - name: Run the GTFS update script
      run: |
        python main.py  # Runs your Python script

    - name: List files
      run: |
        ls -l  # Lists files to check if the data is processed correctly

    - name: Print working directory
      run: |
        pwd  # Prints the current working directory

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"  # Configures git
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update GTFS data" || echo "No changes to commit"  # Commits the updated data
        git push  # Pushes changes to the repository
